### ISSUE TITLE
Signing the assembly

### ISSUE THREAD

**Issue by nshayanfar** [serilog-contrib/serilog-enrichers-globallogcontext#19]
I have a strongly-named assembly which i would like to use your library in. But in order to do that the references must also be strong-named. Would you consider signing global log context?

**Comment by augustoproiete** [comment]
@nshayanfar [The assembly *is* strong-name signed](https://github.com/serilog-contrib/serilog-enrichers-globallogcontext/blob/master/src/Serilog.Enrichers.GlobalLogContext/Serilog.Enrichers.GlobalLogContext.csproj#L20-L22)... What issues do you see when you try to use it?

**Comment by augustoproiete** [comment]
@nshayanfar Feel free to reopen if you see any issue

https://nuget.info/packages/Serilog.Enrichers.GlobalLogContext/1.1.0

<img width="725" alt="image" src="https://user-images.githubusercontent.com/177608/161726320-d6903277-339c-449b-bdc4-e0e76a98b6e1.png">

**Comment by RuslanLatsina** [comment]
Hi @augustoproiete I have an issue to use your package with PowerPoint VSTO project Net472: The error says that there are issues with the signed package. Can you look at it?

![image](https://user-images.githubusercontent.com/20533082/172416010-b0c72496-d129-49ca-b681-a59395fb12d2.png)

Note: Somehow I could reproduce it only with VSTO project

**Comment by augustoproiete** [comment]
Thanks for reporting this error @RuslanLatsina! Could you please create a new issue specific for this, and include a sample project that reproduces this? Also, please let me know if your PowerPoint is 32-bit or 64-bit

**Comment by augustoproiete** [comment]
:tada: The changes implemented in response to this issue shipped with **Serilog.Enrichers.GlobalLogContext v2.0.0**

The release is available on:

- :rocket: [GitHub Release](https://github.com/serilog-contrib/serilog-enrichers-globallogcontext/releases/tag/v2.0.0)
- :package: [NuGet Package](https://www.nuget.org/packages/Serilog.Enrichers.GlobalLogContext/2.0.0)
