### ISSUE TITLE
VSTO project - not able to use GlobalContext which referenced as Nuget package. 

### ISSUE THREAD

**Issue by RuslanLatsina** [serilog-contrib/serilog-enrichers-globallogcontext#27]
I have an issue to use your package with PowerPoint VSTO project Net472: The error says that there are issues with the signed package. 
![image](https://user-images.githubusercontent.com/20533082/172556786-df3afdb1-5e15-401e-a00b-9dad62019744.png)

Test project:

[PowerPointAddIn_GlobalLogContext.zip](https://github.com/serilog-contrib/serilog-enrichers-globallogcontext/files/8859319/PowerPointAddIn_GlobalLogContext.zip)

Test environment: Windows 10 64 bit, Powerpoint 16 64bit
![image](https://user-images.githubusercontent.com/20533082/172557371-96e92bd5-d31f-4ac9-af5c-59c6d3f1dae5.png)

**Comment by sra-michaelgold** [comment]
same issue here for netstandard2.0 reference

**Comment by augustoproiete** [comment]
:tada: The changes implemented in response to this issue shipped with **Serilog.Enrichers.GlobalLogContext v2.0.0**

The release is available on:

- :rocket: [GitHub Release](https://github.com/serilog-contrib/serilog-enrichers-globallogcontext/releases/tag/v2.0.0)
- :package: [NuGet Package](https://www.nuget.org/packages/Serilog.Enrichers.GlobalLogContext/2.0.0)
